anna-money/aio-request

- .github/workflows/ci.yml
- .gitignore
- Makefile
- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/deadline.py
- aio_request/delays_provider.py
- aio_request/models.py
- aio_request/request_sender.py
- aio_request/requests.py
- aio_request/response_classifier.py
- aio_request/strategy.py
- aio_request/utils.py
- requirements-dev.txt
- setup.py
- tests/conftest.py
- tests/test_deadline.py
- tests/test_delays.py
- tests/test_forking_strategy.py
- tests/test_sequential_strategy.py
> First version

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/requests.py
- aio_request/response_classifier.py
- aio_request/strategy.py
- aio_request/utils.py
- setup.py
- tests/conftest.py
> Slightly rework response and request creation

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/log.py
- aio_request/strategy.py
> Improvements of sequential strategy and RequestSender logging

- Makefile
- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/deadline.py
- aio_request/delays_provider.py
- aio_request/priority.py
- aio_request/request_sender.py
- aio_request/requests.py
- aio_request/strategy.py
- aio_request/utils.py
- tests/conftest.py
- tests/test_parallel_strategy.py
- tests/test_sequential_strategy.py
> Priority support & various fixes

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/context.py
- aio_request/deadline.py
- aio_request/log.py
- aio_request/priority.py
- aio_request/strategy.py
- requirements-dev.txt
- tests/conftest.py
- tests/test_aiohttp.py
- tests/test_deadline.py
> Allow to pass deadline and priority via context

- aio_request/aiohttp.py
- aio_request/request_sender.py
> Drop aio prefix from metrics labels and log fields

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/client.py
- aio_request/metrics.py
- aio_request/request_sender.py
- tests/conftest.py
- tests/test_parallel_strategy.py
- tests/test_sequential_strategy.py
- tests/test_setup.py
> Move metrics to transport

- README.md
- requirements-dev.txt
- setup.py
> Add readme and use it in package description

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/requests.py
- aio_request/utils.py
> Add query parameters

- aio_request/__init__.py
- aio_request/aiohttp.py
- tests/conftest.py
- tests/test_aiohttp_middleware.py
> Allow to setup default timeout on aiohttp handlers

- README.md
- aio_request/__init__.py
- aio_request/client.py
- aio_request/strategy.py
- aio_request/utils.py
- tests/test_aiohttp_middleware.py
> Single attempt strategy

- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/client.py
- aio_request/utils.py
> Replace deadline header with timeout

- README.md
- requirements-dev.txt
- tests/test_deadline.py
> Drop zoneinfo backport

- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/client.py
- aio_request/context.py
- aio_request/delays_provider.py
- aio_request/metrics.py
- aio_request/prometheus.py
- aio_request/requests.py
- aio_request/strategy.py
- aio_request/utils.py
- tests/conftest.py
- tests/test_aiohttp_transport.py
- tests/test_utils.py
> Accept any parameters for query&path and stringify them

- .github/workflows/ci.yml
- aio_request/base.py
- aio_request/strategy.py
- aio_request/utils.py
- requirements-dev.txt
- setup.py
- tests/test_deadline.py
> Return python 3.8 to test matrix

- .github/workflows/ci.yml
- aio_request/__init__.py
- aio_request/aiohttp.py
- tests/conftest.py
- tests/test_aiohttp_resolver.py
- tests/test_aiohttp_transport.py
> Add aiohttp dns resolver

- aio_request/prometheus.py
> Allow to customise histogram buckets

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/base.py
- aio_request/client.py
- aio_request/opentelemetry.py
- aio_request/pipeline.py
- aio_request/tracing.py
- requirements-dev.txt
- tests/test_pipeline.py
> Tracing support

- aio_request/base.py
- tests/test_base.py
> Extend headers instead of update

- README.md
- aio_request/__init__.py
- aio_request/base.py
- aio_request/circuit_breaker.py
- aio_request/pipeline.py
- aio_request/response_classifier.py
- aio_request/setup.py
- tests/conftest.py
- tests/test_circuit_breaker.py
- tests/test_setup.py
https://martinfowler.com/bliki/CircuitBreaker.html
```
"""
failure_threshold: The failure threshold at which the circuit will break (a number between 0 and 1)
break_duration: The duration the circuit will stay open before resetting
minimum_throughput: How many actions must pass through the circuit breaker to come into action.
sampling_sampling_duration: The duration when failure ratios are assessed.
"""
```
Example:
```
aio_request.DefaultCircuitBreaker[str, int](
break_duration=1.0,
sampling_duration=1.0,
minimum_throughput=2,
failure_threshold=0.5,
)
```
In case of `requests count` >= `minimum throughput`(>=2) in `sampling period`(1 second) the circuit breaker will open if  `failed requests count`/`total requests count` >= `failure threshold`(50%).
> Circuit breaker

- aio_request/request_strategy.py
> Clean up resources in single shield

- .github/workflows/ci.yml
- Makefile
- setup.py
> Add python 3.10 to CI

- aio_request/response_classifier.py
- tests/test_response_classifier.py
@timuram asked to override ResponseVerdict for response.status.
> Allow to customize DefaultResponseClassifier

- aio_request/aiohttp.py
> Release aiohttp response instead of close

- aio_request/__init__.py
- aio_request/aiohttp.py
- aio_request/base.py
> Validate json content-type

- aio_request/response_classifier.py
- tests/test_response_classifier.py
> Reject throttling(too many requests) status code

- .github/dependabot.yml
- .github/workflows/ci.yml
- Makefile
- aio_request/aiohttp.py
- requirements-dev.txt
- setup.py
> Add python 3.11 support

- CHANGELOG.md
- aio_request/__init__.py
- aio_request/httpx.py
- requirements-dev.txt
- tests/test_transport.py
https://github.com/encode/httpx/
> Support httpx transport

- .github/workflows/ci.yml
- setup.py
https://www.python.org/downloads/release/python-3120/
> Add python 3.12 to CI

- README.md
- aio_request/__init__.py
- aio_request/delays_provider.py
- aio_request/request_strategy.py
- aio_request/setup.py
- tests/test_delays.py
- tests/test_parallel_strategy.py
- tests/test_sequential_strategy.py
Linear delays is very misleading name.
> Rename linear-delays to linear-backoff-delays

- aio_request/__init__.py
- aio_request/client.py
- aio_request/endpoint_provider.py
- aio_request/setup.py
- tests/test_delegate_endpoint_provider.py
This opens two use-cases:
1. How swap of endpoints
2. Lazy load endpoint definition
> Introduce an endpoint provider

- aio_request/client.py
- aio_request/response_classifier.py
- aio_request/setup.py
https://github.com/anna-money/opentelemetry-instrumentation-aio-request
> Move otel support to a separate package

- requirements-dev.txt
- setup.py
- tests/test_utils.py
> Require yarl>=1.12 as aiohttp does

- CHANGELOG.md
- aio_request/__init__.py
- aio_request/pipeline.py
- aio_request/request.py
- aio_request/setup.py
SimpleRequestEnricher should be sync one and do not accept bool parameter.
> Fix request enrichers backward compatibility
